### PR TITLE
Compatibility update for sidekiq 4.0+

### PR DESCRIPTION
**Pull request by davekrupinski**
Update dependencies, middleware, and spec coverage to run successfully against sidekiq 4.0 and higher

### CODE REVIEW

**Comment by ondrejbartas** [comment]
@mhfs @krasnoukhov what with this PR? Can we merged it soon and release new version?

**Comment by archlicher** [comment]
tried it, but the error persists:
`There was an error while trying to load the gem 'sidekiq-failures'.`
`Gem Load Error is: uninitialized constant Sidekiq::Middleware::Server`
`sidekiq-failures-e8571d742f00/lib/sidekiq/failures.rb:72:in block (2 levels) in <top (required)>'`

**Comment by fidelisrafael** [comment]
Sidekiq 5.0.0 removes `Sidekiq::Middleware::Server` as [described here](https://github.com/mperham/sidekiq/blob/3b00587ea0b3f887df9053ee2f6b42a69481b5ce/Changes.md#500)
Basically:

```
Sidekiq::Middleware::Server::RetryJobs -> Sidekiq::JobRetry
Sidekiq::Middleware::Server::Logging -> Sidekiq::JobLogging
```.

**Comment by davekrupinski** [comment]
@archlicher @fidelisrafael Made an update to insert the appropriate retry middleware.  Booted successfully now against sidekiq 5.0 and 4.2.x.

**Comment by fidelisrafael** [comment]
@davekrupinski awesome! I will try in a project that I'm using 5.0.0. May we add a simple tests case to ensure the correct Middleware is returned when `Sidekiq::VERSION` is > 5

**Comment by davekrupinski** [comment]
Tests for correct middleware and passing travis CI.

**Comment by rafiamafia** [comment]
@mhfs any plans on reviewing and merging these changes to master?

**Comment by fidelisrafael** [comment]
For me looks good for merging, anything more you want to do @davekrupinski?

**Comment by mhfs** [comment]
Alright guys, I don't have time to fully test and review this, but I'm taking a leap of faith in name of pushing this forward. Looks well, merging. Thanks for everybody that helped.

**Comment by mhfs** [comment]
Can someone confirm master is running fine on 4 and 5? I'll cut a new release as soon as I get that. Thanks

**Comment by fidelisrafael** [comment]
I will try!

**Comment by fidelisrafael** [comment]
@mhfs @davekrupinski I tried to run with Sidekiq >= 5.0.0 and it's not working, I pushed a small PR #114 which corrects this

**Pull request merged**
