### PR TITLE
limit error message to 500 symbols

### PR DESCRIPTION
**Pull request by antonzaytsev**
I had an issue with queries with lots of params, they are too looooong, may be someone else have similar problems.

### CODE REVIEW

**Comment by krasnoukhov** [comment]
Well, why CSS overflow does not work for you?

**Comment by antonzaytsev** [comment]
@krasnoukhov use CSS overflow is a good way too. Why you think it is better to use CSS overflow instead of just cut error message?

**Comment by krasnoukhov** [comment]
I believe there are at least two reasons for that:

* CSS overflow is already [implemented](https://github.com/mhfs/sidekiq-failures/blob/3b3068df5b8d9674f9005f86c3146f820da56c12/lib/sidekiq/failures/views/failures.erb#L49)
* Message content might potentially contain some useful information but this approach does not allow to see it completely

BTW, which version of the gem do you have?

**Comment by antonzaytsev** [comment]
* CSS overflow implemented not to error message text, but to backtrace. Error message wrapped in tag "a".
* Full error message can be visible when you click on worker class name (http://take.ms/pPk1Z) and get detailed failure page.

Version is the latest master branch.

**Comment by krasnoukhov** [comment]
Well, my bad, I was confused for some reason. This makes sense then.

**Comment by antonzaytsev** [comment]
Thank you, @krasnoukhov!

**Pull request merged**
