### PR TITLE
Guard against error_message being nil

### PR DESCRIPTION
**Pull request by mcasper**
In the event that a failure has no error_message, the sidekiq failures
page will throw an exception:

```
(erb):48:in `block in _erb': undefined method `size' for nil:NilClass (NoMethodError)
    from (erb):31:in `each'
    from (erb):31:in `_erb'
    from /usr/local/rbenv/versions/2.5.1/lib/ruby/2.5.0/erb.rb:876:in `eval'
    from /usr/local/rbenv/versions/2.5.1/lib/ruby/2.5.0/erb.rb:876:in `result'
    from gems/sidekiq-5.2.7/lib/sidekiq/web/action.rb:83:in `_erb'
    from gems/sidekiq-5.2.7/lib/sidekiq/web/action.rb:54:in `erb'
    from gems/sidekiq-5.2.7/lib/sidekiq/web/action.rb:63:in `render'
    from gems/sidekiq-failures-1.0.0/lib/sidekiq/failures/web_extension.rb:25:in `block in registered'
    from gems/sidekiq-5.2.7/lib/sidekiq/web/application.rb:287:in `instance_exec'
    from gems/sidekiq-5.2.7/lib/sidekiq/web/application.rb:287:in `block in call'
    from gems/sidekiq-5.2.7/lib/sidekiq/web/application.rb:283:in `catch'
    from gems/sidekiq-5.2.7/lib/sidekiq/web/application.rb:283:in `call'
    from gems/rack-protection-2.0.5/lib/rack/protection/xss_header.rb:18:in `call'
    from gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
    from gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
    from gems/rack-protection-2.0.5/lib/rack/protection/path_traversal.rb:16:in `call'
    from gems/rack-protection-2.0.5/lib/rack/protection/json_csrf.rb:26:in `call'
    from gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
    from gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
    from gems/rack-protection-2.0.5/lib/rack/protection/frame_options.rb:31:in `call'
    from gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
    from gems/rack-2.0.7/lib/rack/session/abstract/id.rb:232:in `context'
    from gems/rack-2.0.7/lib/rack/session/abstract/id.rb:226:in `call'
    from gems/rack-2.0.7/lib/rack/urlmap.rb:68:in `block in call'
    from gems/rack-2.0.7/lib/rack/urlmap.rb:53:in `each'
    from gems/rack-2.0.7/lib/rack/urlmap.rb:53:in `call'
    from gems/rack-2.0.7/lib/rack/builder.rb:153:in `call'
    from gems/sidekiq-5.2.7/lib/sidekiq/web.rb:103:in `call'
    from gems/sidekiq-5.2.7/lib/sidekiq/web.rb:108:in `call'
```

This is because we're trying to call `.size` on `nil`. This PR first
calls `to_s` on the error_message, ensuring that we'll always have
something that can respond to `.size`.

### CODE REVIEW

**Comment by mcasper** [comment]
@mhfs Is this repo still maintained?

**Comment by mhfs** [comment]
Unfortunately, mostly not, sorry. Are you interested in helping maintain it?

**Comment by mcasper** [comment]
I'd be happy to!

**Comment by mcasper** [comment]
https://github.com/mhfs/sidekiq-failures/pull/123 should gets tests passing again, so I'll focus on getting that in before anything else

**Comment by mcasper** [comment]
@mhfs How do you want to move forward?

**Comment by mcasper** [comment]
@mhfs Just wanted to follow up and say that I'm still interested in helping to maintain this gem

**Comment by mhfs** [comment]
@mcasper I invited you to be a colaborator in this repo. I appreciate your help A LOT.

**Comment by mhfs** [comment]
@mcasper I'll probably continue to be very slow responding to github notifications. please reach me directly at mhfs@icloud.com and we can coordinate a better communication option. Thanks.

**Pull request merged**
