### PR TITLE
add csrf_tag to each form instance

### PR DESCRIPTION
**Pull request by JamesChevalier**
CSRF is required as of sidekiq 3.4.2
https://github.com/mperham/sidekiq/blob/master/Changes.md#342

Without this, you will receive `Failure` as a response to Retry/Delete attempts.

Fixes [#98](https://github.com/mhfs/sidekiq-failures/issues/98)

### CODE REVIEW

**Comment by JamesChevalier** [comment]
Ah, that failure makes sense. :disappointed: 

    NameError: undefined local variable or method `csrf_tag' for #<Sidekiq::Web:0x000000037d1f60>

I don't have a lot of experience with gem development. I'm not sure how to conditionally call `csrf_tag` if the version of `sidekiq` that's in use is 3.4.2 or greater.

**Comment by krasnoukhov** [comment]
Well, I think that `<%= csrf_tag if respond_to?(:csrf_tag) %>` would work :smile:

**Comment by JamesChevalier** [comment]
Good call, thanks for the tip!
(I always thought `respond_to?` could only be called on an object, e.g. `User.respond_to?(:full_name)`).

**Comment by krasnoukhov** [comment]
In this case it's basically `self.respond_to?`. Could you please squash these two commits together so I'll merge this thing?

**Comment by JamesChevalier** [comment]
I ... I have no idea what I've done. :fearful: (I usually work alone, and haven't really done any significant pull requests).
I just tried `git reset --soft HEAD~2`, but that didn't seem to have done anything...
So I tried [this SO answer](http://stackoverflow.com/questions/2563632/how-can-i-merge-two-commits-into-one), but now I've got double the git commits...

I might just close it all out and start from scratch...

**Comment by krasnoukhov** [comment]
Ok, I can rebase the master branch after the merge. Thanks!

**Comment by JamesChevalier** [comment]
Thanks/Sorry!

**Pull request merged**
